### ISSUE TITLE
0.0s Attack and Release makes the note go on forever, even after release

### ISSUE THREAD

**Issue by some1chan** [FigBug/PAPU#1]
Hey, I've just discovered this plugin and it does Gameboy soundchip emulation quite well! I do have an issue about it that seems to be a bug.

If I were to play a note in PAPU with 0.0s attack and any Release number (other than 0.0s), the note will go on forever. I don't believe this is the right behavior and is a bug. In [this video at 1:56](https://youtu.be/5fdB6RdKZcQ?t=116), the behavior is what I'd expect — ~~it doesn't continue on, blasting the waveform into the void as i contemplate my tiny, tiny existence facing the entirety of the universe, fearing the enormity of the infinite. Instead,~~ it stops playing.

I am running this VST in REAPER in Windows 10. Any help would be greatly appreciated! ❤️ 

## Presets
I've attached the presets I've used that were created by PAPU. The first ZIP is how I found the bug, and the second ZIP is essentially what is shown in the video.

- [00attack05release.zip](https://github.com/FigBug/PAPU/files/4801511/00attack05release.zip)
- [videoexample.zip](https://github.com/FigBug/PAPU/files/4801543/videoexample.zip)

**Comment by some1chan** [comment]
Did more testing; turns out the video example will have the same behavior as the first ZIP if the sweep is off.

**Comment by ginrei** [comment]
Same here on AudioUnit, OSX Catalina + Logic Pro X 10.5.1.
Potentially lost note-off?

**Comment by FigBug** [comment]
Just uploaded a new version, please test and let me know if fixed
