### ISSUE TITLE
More Granular Controls

### ISSUE THREAD

**Issue by some1chan** [FigBug/PAPU#2]
I'd like to be able to input seconds as values other than the 0-7 system. Is that possible? For example, I would like to input a 0.2 second attack like in the screenshot on [the website](https://socalabs.com/synths/papu/).

![](https://socalabs.com/wp-content/uploads/2017/08/papu.png)

Is that possible to implement? Thanks!

**Comment by FigBug** [comment]
I'm sticking with what the Gameboy hardware could actually do, so I don't want to add rates the real hardware didn't actually have.
