### ISSUE TITLE
No fonts in PAPU (and other SocaLabs synths) on GNU/Linux

### ISSUE THREAD

**Issue by fpesari** [FigBug/PAPU#3]
Hello, 

when I launch PAPU (and other SocaLabs synths like SN76489) no fonts are loaded:

![papu](https://user-images.githubusercontent.com/52702101/85223846-402fea80-b3c6-11ea-8333-cee2352ea401.png)

My friend @kottv which uses my distro (openSUSE) helped me figure out the problem by running `trace -f`, which shows that PAPU loads the Verdana font, which is proprietary and not present on my system.

Always thanks  to @kottv 's findings, it seems JUCE puts the Verdana font at the top of the GNU/Linux font list in [modules/juce_graphics/native/juce_linux_Fonts.cpp](https://github.com/juce-framework/JUCE/blob/d51a44a58ec686b627d38168e301840288674645/modules/juce_graphics/native/juce_linux_Fonts.cpp), although I never experienced this bug in a JUCE programs before - perhaps most JUCE programs I use manually specify which font to use?

I don't know if this can be fixed in Gin rather than here, I just wanted to know if it would be possible to make so that a generic font family (like Sans) or a specific freely licensed font is loaded by default?

**Comment by KottV** [comment]
The reason is that gin submodule in my package was not updated to https://github.com/FigBug/Gin/commit/b26b3ce2317368807d03c7fc2d6d9e273b0bc54b#diff-d1fe45a17df45d772ff4dc00a3c251e4

Build with recent code fixes hardcoded font dependency.
I'm sorry for inconvenience.

**Comment by fpesari** [comment]
Still, I reported the use of Verdana as the top GNU/Linux font on the JUCE bug tracker. Sorry for the inconvenience, closing.
